plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "C:\\Users\\srija\\Desktop\\srijan portfolio"
publishOrigin = "default"
base = "C:\\Users\\srija\\Desktop\\srijan portfolio"
command = "npm run build"
commandOrigin = "heuristics"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]